version: '3.7'

services:
  db:
    image: "postgres:latest"
    env_file:
      - database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db 
      
volumes:
  postgres_data: